DROP TABLE CARDS;
DROP TABLE accounts;
DROP TABLE logs;
DROP TABLE users;
DROP SEQUENCE SEQ_LOGNO;
CREATE TABLE USERS (
    USERID                  VARCHAR2(255) , /* UserId */
    USERNAME                VARCHAR2(255) NOT NULL, /* Username */
    PASSWORD                VARCHAR2(255) NOT NULL, /* password */
    TRANSACTION_PASSWORD    VARCHAR2(255) NOT NULL, /* Transaction_password */
    CONSTRAINT USERS_PK PRIMARY KEY(USERID)
);

COMMENT ON TABLE USERS IS '사용자 목록';
COMMENT ON COLUMN USERS.USERID IS '아이디';
COMMENT ON COLUMN USERS.USERNAME IS '사용자명';
COMMENT ON COLUMN USERS.PASSWORD IS '비밀번호(숫자 4자리)';
COMMENT ON COLUMN USERS.TRANSACTION_PASSWORD IS '결제 비밀번호';





CREATE TABLE LOGS (
    LOGNO               NUMBER(38,0), /* LogNo */
    UserId              VARCHAR2(255), /* UserId */
    means               VARCHAR2(15) NOT NULL, /* means */
    payment_number      varchar2(255) NOT NULL, /* 결제 수단 */
    deposit             NUMBER(38,0) DEFAULT 0, /* deposit */
    balance             NUMBER(38,0) DEFAULT 0, /* balance */
    mall_id             VARCHAR2(100) NOT NULL, /* mall_id */
    mall_account_number varchar2(255) NOT NULL, /* mall_account_number */
    TRANSACTION_DATE    TIMESTAMP NOT NULL, /* Transaction_date */
    etc                 varchar2(100) DEFAULT '거래 완료',
    CONSTRAINT LOGS_PK PRIMARY key(LOGNO)
);

ALTER TABLE BANK.LOGS MODIFY ETC VARCHAR2(100) DEFAULT '거래 완료';

COMMENT ON TABLE LOGS IS '거래내역';
COMMENT ON COLUMN LOGS.LOGNO IS '고유번호';
COMMENT ON COLUMN LOGS.UserId IS '아이디';
COMMENT ON COLUMN LOGS.TRANSACTION_DATE IS '거래 날짜';
COMMENT ON COLUMN LOGS.deposit IS '거래 액수';
COMMENT ON COLUMN LOGS.balance IS '잔액';
COMMENT ON COLUMN LOGS.mall_id IS '거래처 아이디';
COMMENT ON COLUMN LOGS.mall_account_number IS '거래처 계좌';
COMMENT ON COLUMN LOGS.means IS '결제 수단';
COMMENT ON COLUMN LOGS.payment_number IS '카드 또는 계좌번호';
COMMENT ON COLUMN LOGS.etc IS '비고';

CREATE SEQUENCE SEQ_LOGNO START WITH 1 INCREMENT BY 1 ORDER;

ALTER TABLE logs DROP column mall_name;



CREATE TABLE ACCOUNTS(
    ACCOUNT_NUMBER  VARCHAR2(255),
    USERID          VARCHAR2(255),
    BALANCE         NUMBER(38,0) DEFAULT 0,
    CONSTRAINT ACCOUNTS_PK PRIMARY KEY(ACCOUNT_NUMBER),
    CONSTRAINT ACCOUNTS_FK_TO_USERS FOREIGN KEY(USERID) REFERENCES USERS(USERID) ON DELETE SET NULL
);

COMMENT ON TABLE ACCOUNTS IS '계좌';
COMMENT ON COLUMN ACCOUNTS.ACCOUNT_NUMBER IS '계좌번호';
COMMENT ON COLUMN ACCOUNTS.USERID IS '아이디';
COMMENT ON COLUMN ACCOUNTS.BALANCE IS '잔고';




CREATE TABLE CARDS (
    CARD_NUMBER     VARCHAR2(255) NOT NULL, /* Card_number */
    ACCOUNT_NUMBER  VARCHAR2(255), /* Account_number */
    USERID          VARCHAR2(255), /* UserId */
    CVS             VARCHAR2(255) NOT NULL, /* CVS */
    END_DATE        TIMESTAMP NOT NULL,
    CONSTRAINT CARDS_PK PRIMARY KEY(CARD_NUMBER),
    CONSTRAINT CARDS_FK_TO_USERS FOREIGN KEY(USERID) REFERENCES USERS(USERID) ON DELETE SET null,
    CONSTRAINT CARDS_FK_TO_ACCOUNTS FOREIGN KEY(ACCOUNT_NUMBER) REFERENCES ACCOUNTS(ACCOUNT_NUMBER) ON DELETE SET null
);

COMMENT ON TABLE CARDS IS '카드';
COMMENT ON COLUMN CARDS.CARD_NUMBER IS '카드 번호';
COMMENT ON COLUMN CARDS.ACCOUNT_NUMBER IS '카드와 연결된 계좌번호';
COMMENT ON COLUMN CARDS.USERID IS '아이디';
COMMENT ON COLUMN CARDS.CVS IS '3자리 인식 번호';
COMMENT ON COLUMN CARDS.END_DATE IS '카드 만료일';

ALTER TABLE logs 